print("Ex: Ax^2+Bx+C=0")
a=float(input("Enter the A value: "))
b=float(input("Enter the B value: "))
c=float(input("Enter the C value: "))

b2=((b**2))
b1=(b*-1)
root=(b2-4*a*c)
divisor=(a*2)
quad1=((b1-root)/divisor)
quad2=((b1+root)/divisor)
print("solution set: ""{"+str(quad2)+","+str(quad1)+"}")
